<?php
/** @var array<string,mixed> $report */
/** @var array<string,mixed>|null $workspace */
$r = $report;
$f = $r['funnel'];
$money = static fn (int $c): string => '$' . number_format($c / 100, 2);
?>
<div class="mb-6 border-b border-slate-200 pb-4">
    <div class="text-lg font-bold text-slate-900"><?= e($workspace['name'] ?? 'Workspace') ?></div>
    <div class="text-xs text-slate-400">Recruitment report</div>
</div>

<table class="w-full text-sm">
    <tbody>
        <tr class="border-b border-slate-100"><td class="py-2 text-slate-500">Published jobs</td><td class="py-2 text-right font-semibold text-slate-800"><?= e($r['jobs']['published']) ?> <span class="font-normal text-slate-400">of <?= e($r['jobs']['total']) ?></span></td></tr>
        <tr class="border-b border-slate-100"><td class="py-2 text-slate-500">Applications</td><td class="py-2 text-right font-semibold text-slate-800"><?= e($f['applications']) ?></td></tr>
        <tr class="border-b border-slate-100"><td class="py-2 text-slate-500">Interviews (completed)</td><td class="py-2 text-right font-semibold text-slate-800"><?= e($r['interviews']['completed']) ?><?= $r['interviews']['avg_score'] !== null ? ' · avg ' . e($r['interviews']['avg_score']) : '' ?></td></tr>
        <tr class="border-b border-slate-100"><td class="py-2 text-slate-500">Offers</td><td class="py-2 text-right font-semibold text-slate-800"><?= e($f['offers']) ?> <span class="font-normal text-slate-400">(<?= e($r['offers']['accepted']) ?> accepted)</span></td></tr>
        <tr class="border-b border-slate-100"><td class="py-2 text-slate-500">Hires</td><td class="py-2 text-right font-semibold text-slate-800"><?= e($f['hires']) ?></td></tr>
        <tr><td class="py-2 text-slate-500">AI usage</td><td class="py-2 text-right font-semibold text-slate-800"><?= e($r['ai']['sessions']) ?> runs · <?= e($money((int) $r['ai']['cost_cents'])) ?></td></tr>
    </tbody>
</table>

<?php if (($r['applications_by_status'] ?? []) !== []): ?>
    <h2 class="mt-8 mb-2 text-sm font-semibold text-slate-900">Applications by status</h2>
    <ul class="text-sm">
        <?php foreach ($r['applications_by_status'] as $status => $count): ?>
            <li class="flex justify-between border-b border-slate-50 py-1.5"><span class="capitalize text-slate-600"><?= e(str_replace('_', ' ', (string) $status)) ?></span><span class="font-semibold text-slate-800"><?= e($count) ?></span></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<p class="mt-10 text-xs text-slate-400">Generated by HaHireAI.</p>
