<?php

declare(strict_types=1);

/**
 * Blueprint starter library (docs/51 §6, §11 — AI Interview Engine).
 *
 * Role-family interview blueprints a tenant can INSTANTIATE into its own editable
 * `interview_blueprints` + `blueprint_sections` + `blueprint_section_rules`
 * (App\Services\Blueprint\BlueprintLibrary::instantiateFromLibrary). These are
 * seeds, not hard-coded behaviour — once instantiated they are ordinary tenant data:
 * editable, versionable and feature-flaggable (docs/51 "Configuration-driven").
 * Adding a role blueprint here is a data change, never a code change.
 *
 * Shape of each library entry:
 *   'name'                => display name
 *   'role_family'         => stable role-family key (VARCHAR, code-validated)
 *   'description'         => one-line summary
 *   'objectives'          => string[]  (interview-level goals)
 *   'evaluation_criteria' => string[]  (blueprint-level scoring dimensions)
 *   'sections'            => list of:
 *       'key'                => stable section id (unique within the blueprint)
 *       'title'              => display title
 *       'objective'          => what this section probes
 *       'weight'             => relative weight (the library keeps these summing ~100)
 *       'difficulty'         => 'easy' | 'medium' | 'hard'
 *       'question_strategy'  => how the engine should generate/sequence questions
 *       'scoring_rules'      => string[]  (per-section scoring guidance)
 *       'follow_up_rules'    => string[]  (when/how to dig deeper)
 *       'expected_skills'    => string[]  (skills a strong answer demonstrates)
 *       'expected_behaviors' => string[]  (behaviours a strong candidate shows)
 *
 * On instantiation, question_strategy/scoring_rules/follow_up_rules/expected_skills/
 * expected_behaviors and the blueprint-level evaluation_criteria each become
 * `blueprint_section_rules` rows (rule_type: question_strategy | scoring |
 * follow_up | expected_skill | expected_behavior | evaluation_criteria).
 */
return [
    'library' => [

        // ── Engineering / technical ────────────────────────────────────────
        'junior_backend_developer' => [
            'name'        => 'Junior Backend Developer',
            'role_family' => 'engineering',
            'description' => 'Entry-level backend engineering interview focused on fundamentals and coachability.',
            'objectives'  => [
                'Verify core programming and data-structure fundamentals.',
                'Assess ability to reason about small problems out loud.',
                'Gauge curiosity, coachability and growth potential.',
            ],
            'evaluation_criteria' => [
                'Programming fundamentals',
                'Problem-solving approach',
                'Communication and clarity',
                'Learning attitude',
            ],
            'sections' => [
                [
                    'key' => 'fundamentals', 'title' => 'Programming Fundamentals',
                    'objective' => 'Confirm grasp of language basics, data structures and time/space tradeoffs.',
                    'weight' => 35, 'difficulty' => 'easy',
                    'question_strategy' => 'Start with definitional questions, then ask the candidate to apply a concept to a tiny concrete example.',
                    'scoring_rules' => ['Reward correct use of basic data structures.', 'Penalize confident-but-wrong claims more than honest "I am not sure".'],
                    'follow_up_rules' => ['If an answer is shallow, ask for a concrete example.', 'Probe big-O when a candidate cites efficiency.'],
                    'expected_skills' => ['Arrays, maps and loops', 'Basic time/space complexity', 'Reading a short snippet'],
                    'expected_behaviors' => ['Thinks before answering', 'Admits gaps honestly'],
                ],
                [
                    'key' => 'problem_solving', 'title' => 'Problem Solving',
                    'objective' => 'Watch the candidate decompose a small, well-bounded coding problem.',
                    'weight' => 30, 'difficulty' => 'medium',
                    'question_strategy' => 'Pose one easy coding task; ask them to narrate their plan before coding.',
                    'scoring_rules' => ['Reward a clear plan over a fast-but-messy solution.', 'Credit correct handling of one edge case.'],
                    'follow_up_rules' => ['If stuck, offer a small hint and observe recovery.', 'Ask how they would test the solution.'],
                    'expected_skills' => ['Decomposition', 'Edge-case awareness', 'Basic debugging'],
                    'expected_behaviors' => ['Asks clarifying questions', 'Stays calm when stuck'],
                ],
                [
                    'key' => 'collaboration', 'title' => 'Collaboration & Tooling',
                    'objective' => 'Check familiarity with version control, code review and teamwork.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about git workflow and a time they received feedback on code.',
                    'scoring_rules' => ['Reward openness to feedback.', 'Reward basic git fluency.'],
                    'follow_up_rules' => ['Ask what they changed after a code review.'],
                    'expected_skills' => ['Git basics', 'Reading a diff', 'Writing a clear commit message'],
                    'expected_behaviors' => ['Receptive to feedback', 'Communicates blockers early'],
                ],
                [
                    'key' => 'growth', 'title' => 'Learning & Motivation',
                    'objective' => 'Gauge curiosity and how the candidate learns new technology.',
                    'weight' => 15, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask what they learned most recently and how they approached it.',
                    'scoring_rules' => ['Reward concrete recent learning over generic enthusiasm.'],
                    'follow_up_rules' => ['Ask how they would ramp on an unfamiliar codebase.'],
                    'expected_skills' => ['Self-directed learning', 'Using documentation'],
                    'expected_behaviors' => ['Curious', 'Persistent'],
                ],
            ],
        ],

        'senior_backend_developer' => [
            'name'        => 'Senior Backend Developer',
            'role_family' => 'engineering',
            'description' => 'Senior backend interview covering deep technical skill, system design and leadership.',
            'objectives'  => [
                'Assess depth of backend and distributed-systems expertise.',
                'Evaluate system-design judgement and tradeoff reasoning.',
                'Gauge technical leadership and mentoring.',
            ],
            'evaluation_criteria' => [
                'Technical depth',
                'System design and architecture',
                'Problem-solving under ambiguity',
                'Technical leadership',
                'Communication',
            ],
            'sections' => [
                [
                    'key' => 'technical_assessment', 'title' => 'Technical Assessment',
                    'objective' => 'Probe deep knowledge of languages, databases, concurrency and performance.',
                    'weight' => 30, 'difficulty' => 'hard',
                    'question_strategy' => 'Drill from a claimed strength into edge cases, failure modes and internals.',
                    'scoring_rules' => ['Reward precise mental models of how things work under the hood.', 'Penalize hand-waving on concurrency or consistency.'],
                    'follow_up_rules' => ['Push to failure modes: "what breaks at scale?"', 'Ask for a real incident they debugged.'],
                    'expected_skills' => ['Concurrency and transactions', 'Query optimization', 'Caching strategies', 'API design'],
                    'expected_behaviors' => ['Reasons from first principles', 'Distinguishes facts from guesses'],
                ],
                [
                    'key' => 'system_design', 'title' => 'System Design',
                    'objective' => 'Evaluate ability to design a scalable, reliable backend system.',
                    'weight' => 30, 'difficulty' => 'hard',
                    'question_strategy' => 'Give an open-ended design prompt; require explicit requirements, then iterate on scale.',
                    'scoring_rules' => ['Reward explicit tradeoffs (consistency vs availability, cost vs latency).', 'Reward capacity estimation and bottleneck analysis.'],
                    'follow_up_rules' => ['Increase scale 10x and ask what changes.', 'Inject a failure and ask how the system degrades.'],
                    'expected_skills' => ['Data modeling', 'Horizontal scaling', 'Queues and async processing', 'Observability'],
                    'expected_behaviors' => ['Clarifies requirements first', 'Names assumptions explicitly'],
                ],
                [
                    'key' => 'problem_solving', 'title' => 'Problem Solving',
                    'objective' => 'Assess structured reasoning on a non-trivial, ambiguous problem.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Pose an ambiguous problem; reward clarification and a staged plan.',
                    'scoring_rules' => ['Reward correctness plus complexity analysis.', 'Credit pragmatic tradeoffs.'],
                    'follow_up_rules' => ['Ask to optimize the first solution.', 'Ask how they would test and roll it out.'],
                    'expected_skills' => ['Algorithmic reasoning', 'Complexity analysis', 'Pragmatic tradeoffs'],
                    'expected_behaviors' => ['Handles ambiguity', 'Validates assumptions'],
                ],
                [
                    'key' => 'leadership', 'title' => 'Technical Leadership',
                    'objective' => 'Evaluate mentoring, code-review culture and cross-team influence.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Use behavioral STAR prompts about mentoring and driving a technical decision.',
                    'scoring_rules' => ['Reward evidence of raising the bar for a team.', 'Reward principled disagreement and consensus-building.'],
                    'follow_up_rules' => ['Ask about a technical decision they reversed and why.'],
                    'expected_skills' => ['Mentoring', 'Technical writing', 'Stakeholder communication'],
                    'expected_behaviors' => ['Owns outcomes', 'Builds others up'],
                ],
            ],
        ],

        'frontend_developer' => [
            'name'        => 'Frontend Developer',
            'role_family' => 'engineering',
            'description' => 'Frontend engineering interview covering UI fundamentals, frameworks and performance.',
            'objectives'  => [
                'Assess command of HTML/CSS/JS and a modern framework.',
                'Evaluate component design and state management.',
                'Gauge attention to performance and accessibility.',
            ],
            'evaluation_criteria' => [
                'Core web fundamentals',
                'Component and state design',
                'Performance and accessibility',
                'Collaboration with design',
            ],
            'sections' => [
                [
                    'key' => 'web_fundamentals', 'title' => 'Web Fundamentals',
                    'objective' => 'Confirm solid HTML, CSS and JavaScript foundations.',
                    'weight' => 30, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask layout, box-model and JS event-loop questions tied to concrete UI bugs.',
                    'scoring_rules' => ['Reward correct mental model of the box model and event loop.', 'Penalize framework-only knowledge with no fundamentals.'],
                    'follow_up_rules' => ['Ask why a given layout breaks and how to fix it.'],
                    'expected_skills' => ['Semantic HTML', 'CSS layout (fl/grid)', 'JS closures and async'],
                    'expected_behaviors' => ['Debugs methodically', 'Explains clearly'],
                ],
                [
                    'key' => 'framework_components', 'title' => 'Frameworks & Components',
                    'objective' => 'Evaluate component architecture and state management in a modern framework.',
                    'weight' => 30, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask them to design a reusable component and discuss state ownership.',
                    'scoring_rules' => ['Reward clear separation of concerns.', 'Reward sound state-management choices.'],
                    'follow_up_rules' => ['Ask how they would test the component.', 'Probe re-render and memoization tradeoffs.'],
                    'expected_skills' => ['Component composition', 'State management', 'Hooks/lifecycle'],
                    'expected_behaviors' => ['Designs for reuse', 'Thinks about edge states'],
                ],
                [
                    'key' => 'performance_a11y', 'title' => 'Performance & Accessibility',
                    'objective' => 'Assess awareness of rendering performance and accessible UI.',
                    'weight' => 22, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how to diagnose a slow page and make a widget accessible.',
                    'scoring_rules' => ['Reward use of real tooling (profiler, Lighthouse).', 'Reward ARIA and keyboard-nav awareness.'],
                    'follow_up_rules' => ['Ask to prioritize fixes by user impact.'],
                    'expected_skills' => ['Bundle/render optimization', 'Accessibility (a11y)', 'Core Web Vitals'],
                    'expected_behaviors' => ['User-empathetic', 'Data-driven'],
                ],
                [
                    'key' => 'collaboration', 'title' => 'Design Collaboration',
                    'objective' => 'Gauge how the candidate works with designers and product.',
                    'weight' => 18, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about turning an ambiguous design into a shipped feature.',
                    'scoring_rules' => ['Reward proactive clarification with design.'],
                    'follow_up_rules' => ['Ask how they handle a design that hurts performance.'],
                    'expected_skills' => ['Reading design specs', 'Pixel fidelity vs pragmatism'],
                    'expected_behaviors' => ['Collaborative', 'Pragmatic'],
                ],
            ],
        ],

        'devops_engineer' => [
            'name'        => 'DevOps Engineer',
            'role_family' => 'engineering',
            'description' => 'DevOps/SRE interview covering CI/CD, infrastructure, observability and incident response.',
            'objectives'  => [
                'Assess automation, IaC and CI/CD expertise.',
                'Evaluate reliability, observability and incident handling.',
                'Gauge security and cost awareness.',
            ],
            'evaluation_criteria' => [
                'Automation and IaC',
                'Reliability and observability',
                'Incident response',
                'Security and cost awareness',
            ],
            'sections' => [
                [
                    'key' => 'cicd_automation', 'title' => 'CI/CD & Automation',
                    'objective' => 'Probe pipeline design, infrastructure-as-code and release strategy.',
                    'weight' => 28, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask them to design a deployment pipeline and discuss rollback strategy.',
                    'scoring_rules' => ['Reward safe, automated rollbacks.', 'Reward IaC and reproducibility.'],
                    'follow_up_rules' => ['Ask how a bad deploy is detected and reverted.'],
                    'expected_skills' => ['CI/CD pipelines', 'Infrastructure as code', 'Containers/orchestration'],
                    'expected_behaviors' => ['Automates toil', 'Thinks in safety nets'],
                ],
                [
                    'key' => 'reliability', 'title' => 'Reliability & Observability',
                    'objective' => 'Assess SLOs, monitoring and capacity planning.',
                    'weight' => 27, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask how they would make a flaky service reliable and observable.',
                    'scoring_rules' => ['Reward SLOs/error budgets.', 'Reward actionable alerting over noise.'],
                    'follow_up_rules' => ['Ask what they would graph first during an outage.'],
                    'expected_skills' => ['Monitoring and alerting', 'SLOs and error budgets', 'Capacity planning'],
                    'expected_behaviors' => ['Data-driven', 'Reduces noise'],
                ],
                [
                    'key' => 'incident_response', 'title' => 'Incident Response',
                    'objective' => 'Evaluate behaviour under a live production incident.',
                    'weight' => 25, 'difficulty' => 'hard',
                    'question_strategy' => 'Walk through a realistic outage scenario and observe triage.',
                    'scoring_rules' => ['Reward calm, structured triage.', 'Reward blameless postmortem mindset.'],
                    'follow_up_rules' => ['Ask what they would change to prevent recurrence.'],
                    'expected_skills' => ['Triage and mitigation', 'Root-cause analysis', 'Postmortems'],
                    'expected_behaviors' => ['Calm under pressure', 'Blameless and learning-oriented'],
                ],
                [
                    'key' => 'security_cost', 'title' => 'Security & Cost',
                    'objective' => 'Check secure-by-default practices and cloud cost awareness.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about securing secrets and controlling cloud spend.',
                    'scoring_rules' => ['Reward least-privilege and secret hygiene.', 'Reward cost-visibility practices.'],
                    'follow_up_rules' => ['Ask how they would right-size an over-provisioned cluster.'],
                    'expected_skills' => ['Secrets management', 'Least privilege', 'Cloud cost optimization'],
                    'expected_behaviors' => ['Security-minded', 'Cost-conscious'],
                ],
            ],
        ],

        'ai_engineer' => [
            'name'        => 'AI Engineer',
            'role_family' => 'engineering',
            'description' => 'AI/ML engineering interview covering modeling, ML systems and responsible AI.',
            'objectives'  => [
                'Assess ML fundamentals and applied modeling skill.',
                'Evaluate ML-systems and data-pipeline design.',
                'Gauge responsible-AI and evaluation rigor.',
            ],
            'evaluation_criteria' => [
                'ML fundamentals',
                'Applied modeling and evaluation',
                'ML systems and MLOps',
                'Responsible AI',
            ],
            'sections' => [
                [
                    'key' => 'ml_fundamentals', 'title' => 'ML Fundamentals',
                    'objective' => 'Probe understanding of modeling, training and evaluation.',
                    'weight' => 28, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask about bias/variance, overfitting and choosing the right metric for a task.',
                    'scoring_rules' => ['Reward correct metric selection for the problem.', 'Penalize accuracy-only thinking on imbalanced data.'],
                    'follow_up_rules' => ['Ask how they would detect and fix overfitting.'],
                    'expected_skills' => ['Model evaluation', 'Regularization', 'Feature engineering'],
                    'expected_behaviors' => ['Rigorous', 'Skeptical of metrics'],
                ],
                [
                    'key' => 'applied_modeling', 'title' => 'Applied Modeling',
                    'objective' => 'Evaluate framing a real problem as an ML task end to end.',
                    'weight' => 27, 'difficulty' => 'hard',
                    'question_strategy' => 'Give a business problem; require data, baseline, metric and iteration plan.',
                    'scoring_rules' => ['Reward a strong baseline before complexity.', 'Reward offline/online evaluation plan.'],
                    'follow_up_rules' => ['Ask how they would ship and monitor the model.'],
                    'expected_skills' => ['Problem framing', 'Baselines', 'Experiment design'],
                    'expected_behaviors' => ['Pragmatic', 'Iterative'],
                ],
                [
                    'key' => 'ml_systems', 'title' => 'ML Systems & MLOps',
                    'objective' => 'Assess serving, pipelines, monitoring and drift handling.',
                    'weight' => 25, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask them to design a training-to-serving pipeline with monitoring.',
                    'scoring_rules' => ['Reward reproducible pipelines.', 'Reward drift and quality monitoring.'],
                    'follow_up_rules' => ['Ask how they detect and respond to data drift.'],
                    'expected_skills' => ['Model serving', 'Data pipelines', 'Monitoring and drift detection'],
                    'expected_behaviors' => ['Systems thinker', 'Operationally minded'],
                ],
                [
                    'key' => 'responsible_ai', 'title' => 'Responsible AI',
                    'objective' => 'Check awareness of fairness, safety and evaluation for harm.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they would assess a model for bias and unsafe outputs.',
                    'scoring_rules' => ['Reward concrete fairness/safety evaluation.', 'Reward human-in-the-loop where appropriate.'],
                    'follow_up_rules' => ['Ask about a tradeoff between accuracy and fairness.'],
                    'expected_skills' => ['Bias evaluation', 'Safety testing', 'Privacy awareness'],
                    'expected_behaviors' => ['Ethically aware', 'Cautious with impact'],
                ],
            ],
        ],

        'engineering' => [
            'name'        => 'Engineering (General)',
            'role_family' => 'engineering',
            'description' => 'General engineering interview adaptable across software and technical disciplines.',
            'objectives'  => [
                'Assess core technical competence for the discipline.',
                'Evaluate problem-solving and design judgement.',
                'Gauge collaboration and ownership.',
            ],
            'evaluation_criteria' => [
                'Technical competence',
                'Problem solving',
                'Design and tradeoffs',
                'Collaboration and ownership',
            ],
            'sections' => [
                [
                    'key' => 'technical_assessment', 'title' => 'Technical Assessment',
                    'objective' => 'Probe core knowledge in the candidate\'s engineering domain.',
                    'weight' => 30, 'difficulty' => 'hard',
                    'question_strategy' => 'Anchor on a claimed strength, then probe depth and edge cases.',
                    'scoring_rules' => ['Reward depth and correctness.', 'Penalize confident inaccuracies.'],
                    'follow_up_rules' => ['Push from "what" to "why" and "what breaks".'],
                    'expected_skills' => ['Domain fundamentals', 'Tooling fluency', 'Debugging'],
                    'expected_behaviors' => ['Reasons from principles', 'Honest about limits'],
                ],
                [
                    'key' => 'problem_solving', 'title' => 'Problem Solving',
                    'objective' => 'Evaluate structured decomposition of an open problem.',
                    'weight' => 28, 'difficulty' => 'medium',
                    'question_strategy' => 'Pose an ambiguous problem; reward clarification and a staged plan.',
                    'scoring_rules' => ['Reward clarity of approach.', 'Credit edge-case handling.'],
                    'follow_up_rules' => ['Offer a hint when stuck and observe recovery.'],
                    'expected_skills' => ['Decomposition', 'Tradeoff analysis', 'Testing mindset'],
                    'expected_behaviors' => ['Asks good questions', 'Stays composed'],
                ],
                [
                    'key' => 'design', 'title' => 'Design & Architecture',
                    'objective' => 'Assess design judgement and tradeoff reasoning.',
                    'weight' => 24, 'difficulty' => 'hard',
                    'question_strategy' => 'Give a design prompt; require requirements and explicit tradeoffs.',
                    'scoring_rules' => ['Reward explicit tradeoffs.', 'Reward simplicity where possible.'],
                    'follow_up_rules' => ['Change a constraint and ask what changes.'],
                    'expected_skills' => ['Architecture', 'Scalability', 'Maintainability'],
                    'expected_behaviors' => ['Clarifies first', 'Names assumptions'],
                ],
                [
                    'key' => 'collaboration', 'title' => 'Collaboration & Ownership',
                    'objective' => 'Gauge teamwork, communication and accountability.',
                    'weight' => 18, 'difficulty' => 'easy',
                    'question_strategy' => 'Use STAR prompts on a project they owned with others.',
                    'scoring_rules' => ['Reward ownership of outcomes.', 'Reward clear communication.'],
                    'follow_up_rules' => ['Ask about a conflict and its resolution.'],
                    'expected_skills' => ['Communication', 'Code/peer review', 'Planning'],
                    'expected_behaviors' => ['Accountable', 'Collaborative'],
                ],
            ],
        ],

        // ── People / business ──────────────────────────────────────────────
        'hr_specialist' => [
            'name'        => 'HR Specialist',
            'role_family' => 'human_resources',
            'description' => 'HR specialist interview covering people operations, behavior and culture.',
            'objectives'  => [
                'Assess HR domain knowledge and process rigor.',
                'Evaluate empathy, judgement and discretion.',
                'Gauge culture and values alignment.',
            ],
            'evaluation_criteria' => [
                'HR domain knowledge',
                'Behavioral judgement',
                'Communication and empathy',
                'Culture and values fit',
            ],
            'sections' => [
                [
                    'key' => 'hr_knowledge', 'title' => 'HR Domain Knowledge',
                    'objective' => 'Probe knowledge of recruiting, employee relations and compliance basics.',
                    'weight' => 28, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask scenario questions about hiring, onboarding and policy application.',
                    'scoring_rules' => ['Reward fair, consistent process.', 'Reward awareness of compliance constraints.'],
                    'follow_up_rules' => ['Ask how they would handle a policy exception request.'],
                    'expected_skills' => ['Recruiting process', 'Employee relations', 'HR compliance basics'],
                    'expected_behaviors' => ['Fair-minded', 'Process-oriented'],
                ],
                [
                    'key' => 'behavioral', 'title' => 'Behavioral & Conflict Handling',
                    'objective' => 'Evaluate handling of sensitive interpersonal situations.',
                    'weight' => 27, 'difficulty' => 'medium',
                    'question_strategy' => 'Use STAR prompts on a difficult employee or manager situation.',
                    'scoring_rules' => ['Reward empathy plus firmness.', 'Reward confidentiality and tact.'],
                    'follow_up_rules' => ['Ask what they would do differently in hindsight.'],
                    'expected_skills' => ['Conflict resolution', 'Active listening', 'Mediation'],
                    'expected_behaviors' => ['Discreet', 'Calm and balanced'],
                ],
                [
                    'key' => 'communication', 'title' => 'Communication & Influence',
                    'objective' => 'Assess clarity and ability to influence without authority.',
                    'weight' => 25, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they coached a manager or rolled out an unpopular policy.',
                    'scoring_rules' => ['Reward clear, tailored communication.', 'Reward stakeholder buy-in.'],
                    'follow_up_rules' => ['Ask how they handled pushback.'],
                    'expected_skills' => ['Stakeholder management', 'Written communication', 'Coaching'],
                    'expected_behaviors' => ['Persuasive', 'Tactful'],
                ],
                [
                    'key' => 'culture_fit', 'title' => 'Culture & Values',
                    'objective' => 'Gauge alignment with company values and people-first mindset.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about the kind of culture they help build and protect.',
                    'scoring_rules' => ['Reward concrete examples of shaping culture.'],
                    'follow_up_rules' => ['Ask about a value they would defend under pressure.'],
                    'expected_skills' => ['Culture building', 'Inclusion awareness'],
                    'expected_behaviors' => ['Values-driven', 'People-first'],
                ],
            ],
        ],

        'sales_representative' => [
            'name'        => 'Sales Representative',
            'role_family' => 'sales',
            'description' => 'Sales rep interview covering persuasion, product knowledge and resilience.',
            'objectives'  => [
                'Assess persuasion and closing ability.',
                'Evaluate discovery and product knowledge.',
                'Gauge resilience and drive.',
            ],
            'evaluation_criteria' => [
                'Persuasion and closing',
                'Discovery and listening',
                'Product knowledge',
                'Resilience and drive',
            ],
            'sections' => [
                [
                    'key' => 'persuasion', 'title' => 'Persuasion & Closing',
                    'objective' => 'Evaluate ability to handle objections and drive to a close.',
                    'weight' => 30, 'difficulty' => 'medium',
                    'question_strategy' => 'Run a short role-play; raise an objection and observe the response.',
                    'scoring_rules' => ['Reward objection handling that addresses the real concern.', 'Reward a clear, confident ask for the close.'],
                    'follow_up_rules' => ['Escalate the objection and observe composure.'],
                    'expected_skills' => ['Objection handling', 'Negotiation', 'Closing techniques'],
                    'expected_behaviors' => ['Confident', 'Customer-focused'],
                ],
                [
                    'key' => 'discovery', 'title' => 'Discovery & Listening',
                    'objective' => 'Assess needs discovery and qualification.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they qualify a lead and uncover pain points.',
                    'scoring_rules' => ['Reward open questions that uncover needs.', 'Reward qualifying out bad-fit deals.'],
                    'follow_up_rules' => ['Ask how they prioritize a noisy pipeline.'],
                    'expected_skills' => ['Needs discovery', 'Qualification frameworks', 'Active listening'],
                    'expected_behaviors' => ['Curious', 'Listens more than talks'],
                ],
                [
                    'key' => 'product_knowledge', 'title' => 'Product Knowledge',
                    'objective' => 'Check ability to learn and articulate product value.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask them to pitch a familiar product and tie features to value.',
                    'scoring_rules' => ['Reward value framing over feature dumping.', 'Reward tailoring to a persona.'],
                    'follow_up_rules' => ['Ask how they would handle a competitor comparison.'],
                    'expected_skills' => ['Value selling', 'Competitive positioning', 'Quick product ramp'],
                    'expected_behaviors' => ['Prepared', 'Adaptable'],
                ],
                [
                    'key' => 'resilience', 'title' => 'Resilience & Drive',
                    'objective' => 'Gauge persistence, quota mindset and handling rejection.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about a tough quarter and how they recovered.',
                    'scoring_rules' => ['Reward bounce-back and accountability.'],
                    'follow_up_rules' => ['Ask how they keep motivation after losses.'],
                    'expected_skills' => ['Pipeline discipline', 'Goal orientation'],
                    'expected_behaviors' => ['Resilient', 'Self-motivated'],
                ],
            ],
        ],

        'business_development' => [
            'name'        => 'Business Development',
            'role_family' => 'sales',
            'description' => 'Business development interview covering partnerships, strategy and deal-making.',
            'objectives'  => [
                'Assess strategic thinking and market insight.',
                'Evaluate partnership and deal-making skill.',
                'Gauge relationship building and influence.',
            ],
            'evaluation_criteria' => [
                'Strategic thinking',
                'Deal-making and negotiation',
                'Relationship building',
                'Execution and follow-through',
            ],
            'sections' => [
                [
                    'key' => 'strategy', 'title' => 'Strategy & Market Insight',
                    'objective' => 'Evaluate ability to spot and size opportunities.',
                    'weight' => 28, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask them to identify a new market or partnership and justify it.',
                    'scoring_rules' => ['Reward data-backed reasoning.', 'Reward clear prioritization.'],
                    'follow_up_rules' => ['Ask how they would validate the opportunity cheaply.'],
                    'expected_skills' => ['Market analysis', 'Opportunity sizing', 'Business modeling'],
                    'expected_behaviors' => ['Strategic', 'Analytical'],
                ],
                [
                    'key' => 'deal_making', 'title' => 'Deal-Making & Negotiation',
                    'objective' => 'Assess structuring and negotiating partnerships.',
                    'weight' => 27, 'difficulty' => 'hard',
                    'question_strategy' => 'Walk through a complex deal they structured end to end.',
                    'scoring_rules' => ['Reward win-win structuring.', 'Reward knowing walk-away terms.'],
                    'follow_up_rules' => ['Ask about a deal that fell through and lessons learned.'],
                    'expected_skills' => ['Negotiation', 'Deal structuring', 'Contracts basics'],
                    'expected_behaviors' => ['Principled', 'Outcome-driven'],
                ],
                [
                    'key' => 'relationships', 'title' => 'Relationship Building',
                    'objective' => 'Evaluate building trust with partners and stakeholders.',
                    'weight' => 25, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they built a long-term partner relationship.',
                    'scoring_rules' => ['Reward long-term trust over short-term wins.'],
                    'follow_up_rules' => ['Ask how they repaired a strained relationship.'],
                    'expected_skills' => ['Networking', 'Stakeholder management', 'Influence'],
                    'expected_behaviors' => ['Trustworthy', 'Relational'],
                ],
                [
                    'key' => 'execution', 'title' => 'Execution & Follow-Through',
                    'objective' => 'Gauge turning strategy into shipped results.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they drove a partnership from signed to launched.',
                    'scoring_rules' => ['Reward measurable outcomes.'],
                    'follow_up_rules' => ['Ask how they kept momentum across teams.'],
                    'expected_skills' => ['Project coordination', 'Cross-functional execution'],
                    'expected_behaviors' => ['Persistent', 'Organized'],
                ],
            ],
        ],

        'marketing_specialist' => [
            'name'        => 'Marketing Specialist',
            'role_family' => 'marketing',
            'description' => 'Marketing interview covering strategy, creativity, channels and analytics.',
            'objectives'  => [
                'Assess marketing strategy and audience understanding.',
                'Evaluate creativity and content judgement.',
                'Gauge analytics and channel optimization.',
            ],
            'evaluation_criteria' => [
                'Marketing strategy',
                'Creativity and messaging',
                'Channel and campaign execution',
                'Analytics and measurement',
            ],
            'sections' => [
                [
                    'key' => 'strategy', 'title' => 'Marketing Strategy',
                    'objective' => 'Evaluate audience segmentation and positioning.',
                    'weight' => 28, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask them to outline a go-to-market for a sample product.',
                    'scoring_rules' => ['Reward clear target audience and positioning.', 'Reward measurable goals.'],
                    'follow_up_rules' => ['Ask how they would adjust with half the budget.'],
                    'expected_skills' => ['Segmentation', 'Positioning', 'GTM planning'],
                    'expected_behaviors' => ['Strategic', 'Customer-centric'],
                ],
                [
                    'key' => 'creativity', 'title' => 'Creativity & Messaging',
                    'objective' => 'Assess content ideas and message clarity.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask for a campaign concept and the core message behind it.',
                    'scoring_rules' => ['Reward a sharp, memorable message.', 'Reward audience fit.'],
                    'follow_up_rules' => ['Ask how they would A/B test the message.'],
                    'expected_skills' => ['Copywriting', 'Brand voice', 'Campaign ideation'],
                    'expected_behaviors' => ['Creative', 'Audience-aware'],
                ],
                [
                    'key' => 'channels', 'title' => 'Channels & Execution',
                    'objective' => 'Evaluate channel selection and campaign execution.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they would allocate budget across channels and why.',
                    'scoring_rules' => ['Reward channel-fit reasoning.', 'Reward iterative optimization.'],
                    'follow_up_rules' => ['Ask how they handle an underperforming channel.'],
                    'expected_skills' => ['Paid/organic channels', 'SEO/SEM', 'Lifecycle marketing'],
                    'expected_behaviors' => ['Pragmatic', 'Test-driven'],
                ],
                [
                    'key' => 'analytics', 'title' => 'Analytics & Measurement',
                    'objective' => 'Check ability to measure and optimize with data.',
                    'weight' => 22, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask which metrics define success and how they would report them.',
                    'scoring_rules' => ['Reward focus on outcome metrics, not vanity.', 'Reward attribution awareness.'],
                    'follow_up_rules' => ['Ask how they would diagnose a drop in conversions.'],
                    'expected_skills' => ['Marketing analytics', 'Attribution', 'Funnel optimization'],
                    'expected_behaviors' => ['Data-driven', 'Curious'],
                ],
            ],
        ],

        'project_manager' => [
            'name'        => 'Project Manager',
            'role_family' => 'operations',
            'description' => 'Project/program manager interview covering planning, stakeholders and delivery.',
            'objectives'  => [
                'Assess planning and risk management.',
                'Evaluate stakeholder communication.',
                'Gauge delivery and execution discipline.',
            ],
            'evaluation_criteria' => [
                'Planning and prioritization',
                'Risk and dependency management',
                'Stakeholder communication',
                'Delivery and execution',
            ],
            'sections' => [
                [
                    'key' => 'planning', 'title' => 'Planning & Prioritization',
                    'objective' => 'Evaluate scoping, estimation and prioritization.',
                    'weight' => 28, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they planned a project with unclear scope.',
                    'scoring_rules' => ['Reward explicit scope and tradeoffs.', 'Reward realistic estimates.'],
                    'follow_up_rules' => ['Ask how they handled scope creep.'],
                    'expected_skills' => ['Roadmapping', 'Estimation', 'Prioritization frameworks'],
                    'expected_behaviors' => ['Organized', 'Decisive'],
                ],
                [
                    'key' => 'risk', 'title' => 'Risk & Dependencies',
                    'objective' => 'Assess identifying and mitigating risks and dependencies.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about a project that nearly slipped and how they recovered.',
                    'scoring_rules' => ['Reward early risk identification.', 'Reward concrete mitigations.'],
                    'follow_up_rules' => ['Ask how they manage cross-team dependencies.'],
                    'expected_skills' => ['Risk management', 'Dependency tracking', 'Contingency planning'],
                    'expected_behaviors' => ['Proactive', 'Calm under pressure'],
                ],
                [
                    'key' => 'stakeholders', 'title' => 'Stakeholder Communication',
                    'objective' => 'Evaluate communication with stakeholders and leadership.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they communicated bad news to stakeholders.',
                    'scoring_rules' => ['Reward transparent, timely communication.', 'Reward tailoring to the audience.'],
                    'follow_up_rules' => ['Ask how they aligned conflicting stakeholders.'],
                    'expected_skills' => ['Stakeholder management', 'Status reporting', 'Expectation setting'],
                    'expected_behaviors' => ['Transparent', 'Diplomatic'],
                ],
                [
                    'key' => 'delivery', 'title' => 'Delivery & Execution',
                    'objective' => 'Gauge driving projects to on-time, quality delivery.',
                    'weight' => 22, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about a project they delivered and how they tracked progress.',
                    'scoring_rules' => ['Reward measurable delivery outcomes.'],
                    'follow_up_rules' => ['Ask how they unblocked a stalled team.'],
                    'expected_skills' => ['Agile/Scrum', 'Tracking and metrics', 'Facilitation'],
                    'expected_behaviors' => ['Accountable', 'Results-driven'],
                ],
            ],
        ],

        'customer_support' => [
            'name'        => 'Customer Support',
            'role_family' => 'support',
            'description' => 'Customer support interview covering empathy, problem solving and product knowledge.',
            'objectives'  => [
                'Assess empathy and communication.',
                'Evaluate problem solving and troubleshooting.',
                'Gauge product knowledge and patience.',
            ],
            'evaluation_criteria' => [
                'Empathy and communication',
                'Problem solving',
                'Product knowledge',
                'Patience and composure',
            ],
            'sections' => [
                [
                    'key' => 'empathy', 'title' => 'Empathy & Communication',
                    'objective' => 'Evaluate handling an upset customer with empathy and clarity.',
                    'weight' => 30, 'difficulty' => 'easy',
                    'question_strategy' => 'Role-play an angry customer and observe tone and de-escalation.',
                    'scoring_rules' => ['Reward acknowledging feelings before solving.', 'Reward clear, jargon-free language.'],
                    'follow_up_rules' => ['Escalate the customer\'s frustration and observe composure.'],
                    'expected_skills' => ['Active listening', 'De-escalation', 'Clear writing'],
                    'expected_behaviors' => ['Empathetic', 'Patient'],
                ],
                [
                    'key' => 'problem_solving', 'title' => 'Problem Solving',
                    'objective' => 'Assess troubleshooting a customer issue methodically.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Give a vague bug report and observe how they narrow it down.',
                    'scoring_rules' => ['Reward systematic isolation of the cause.', 'Reward knowing when to escalate.'],
                    'follow_up_rules' => ['Ask what they would do if the fix is unknown.'],
                    'expected_skills' => ['Troubleshooting', 'Reproduction steps', 'Escalation judgement'],
                    'expected_behaviors' => ['Methodical', 'Resourceful'],
                ],
                [
                    'key' => 'product_knowledge', 'title' => 'Product Knowledge',
                    'objective' => 'Check ability to learn and explain product details.',
                    'weight' => 24, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask them to explain a feature simply to a non-technical user.',
                    'scoring_rules' => ['Reward accurate, simple explanations.'],
                    'follow_up_rules' => ['Ask how they keep up with product changes.'],
                    'expected_skills' => ['Product fluency', 'Documentation use', 'Simplifying complexity'],
                    'expected_behaviors' => ['Curious', 'Helpful'],
                ],
                [
                    'key' => 'composure', 'title' => 'Patience & Composure',
                    'objective' => 'Gauge staying calm and consistent under repetitive pressure.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about a high-volume or repetitive period and how they coped.',
                    'scoring_rules' => ['Reward consistency and self-management.'],
                    'follow_up_rules' => ['Ask how they avoid burnout while staying caring.'],
                    'expected_skills' => ['Time management', 'Self-regulation'],
                    'expected_behaviors' => ['Patient', 'Composed'],
                ],
            ],
        ],

        'call_center' => [
            'name'        => 'Call Center Agent',
            'role_family' => 'support',
            'description' => 'Call center agent interview covering communication, handling volume and compliance.',
            'objectives'  => [
                'Assess phone communication and clarity.',
                'Evaluate handling pressure and call volume.',
                'Gauge adherence to script and compliance.',
            ],
            'evaluation_criteria' => [
                'Phone communication',
                'Composure under volume',
                'Issue resolution',
                'Compliance and accuracy',
            ],
            'sections' => [
                [
                    'key' => 'communication', 'title' => 'Phone Communication',
                    'objective' => 'Evaluate verbal clarity, tone and listening on calls.',
                    'weight' => 30, 'difficulty' => 'easy',
                    'question_strategy' => 'Role-play a routine call; assess greeting, listening and clarity.',
                    'scoring_rules' => ['Reward warm, clear tone.', 'Reward confirming understanding.'],
                    'follow_up_rules' => ['Introduce a confused caller and observe adaptation.'],
                    'expected_skills' => ['Verbal communication', 'Active listening', 'Clear articulation'],
                    'expected_behaviors' => ['Friendly', 'Attentive'],
                ],
                [
                    'key' => 'pressure', 'title' => 'Composure Under Volume',
                    'objective' => 'Assess staying effective under back-to-back calls and irate callers.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Role-play an irate caller and observe de-escalation under time pressure.',
                    'scoring_rules' => ['Reward calm de-escalation.', 'Reward maintaining pace without rushing the caller.'],
                    'follow_up_rules' => ['Add time pressure and observe quality.'],
                    'expected_skills' => ['De-escalation', 'Time management', 'Multitasking'],
                    'expected_behaviors' => ['Calm', 'Resilient'],
                ],
                [
                    'key' => 'resolution', 'title' => 'Issue Resolution',
                    'objective' => 'Evaluate resolving the caller\'s issue efficiently.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Give a common issue and observe first-call-resolution approach.',
                    'scoring_rules' => ['Reward first-call resolution.', 'Reward correct escalation when needed.'],
                    'follow_up_rules' => ['Ask how they handle an issue outside their authority.'],
                    'expected_skills' => ['Troubleshooting', 'System navigation', 'Escalation judgement'],
                    'expected_behaviors' => ['Efficient', 'Solution-oriented'],
                ],
                [
                    'key' => 'compliance', 'title' => 'Compliance & Accuracy',
                    'objective' => 'Check adherence to scripts, disclosures and data accuracy.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask why scripts and disclosures matter and how they ensure accuracy.',
                    'scoring_rules' => ['Reward respect for required disclosures.', 'Reward careful data entry.'],
                    'follow_up_rules' => ['Ask about a time accuracy mattered most.'],
                    'expected_skills' => ['Script adherence', 'Data accuracy', 'Privacy awareness'],
                    'expected_behaviors' => ['Detail-oriented', 'Rule-following'],
                ],
            ],
        ],

        'finance' => [
            'name'        => 'Finance Professional',
            'role_family' => 'finance',
            'description' => 'Finance interview covering analysis, controls, modeling and judgement.',
            'objectives'  => [
                'Assess financial analysis and modeling.',
                'Evaluate controls and accuracy.',
                'Gauge business judgement and communication.',
            ],
            'evaluation_criteria' => [
                'Financial analysis',
                'Modeling and accuracy',
                'Controls and compliance',
                'Business judgement',
            ],
            'sections' => [
                [
                    'key' => 'analysis', 'title' => 'Financial Analysis',
                    'objective' => 'Probe interpretation of statements and key metrics.',
                    'weight' => 30, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask them to analyze a scenario and identify the key financial drivers.',
                    'scoring_rules' => ['Reward correct interpretation of statements.', 'Reward focus on the material drivers.'],
                    'follow_up_rules' => ['Ask what would change their conclusion.'],
                    'expected_skills' => ['Financial statements', 'Ratio analysis', 'Variance analysis'],
                    'expected_behaviors' => ['Analytical', 'Detail-oriented'],
                ],
                [
                    'key' => 'modeling', 'title' => 'Modeling & Accuracy',
                    'objective' => 'Assess building and sanity-checking a financial model.',
                    'weight' => 26, 'difficulty' => 'hard',
                    'question_strategy' => 'Walk through how they would structure a forecast or valuation model.',
                    'scoring_rules' => ['Reward clear assumptions and structure.', 'Reward sanity checks and error-proofing.'],
                    'follow_up_rules' => ['Ask how they validate a model\'s output.'],
                    'expected_skills' => ['Forecasting', 'Valuation/DCF basics', 'Spreadsheet rigor'],
                    'expected_behaviors' => ['Precise', 'Skeptical'],
                ],
                [
                    'key' => 'controls', 'title' => 'Controls & Compliance',
                    'objective' => 'Evaluate awareness of controls, audit and compliance.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about a control they implemented or a compliance issue they caught.',
                    'scoring_rules' => ['Reward strong internal-control mindset.', 'Reward ethical handling of pressure.'],
                    'follow_up_rules' => ['Ask how they would respond to pressure to misstate a number.'],
                    'expected_skills' => ['Internal controls', 'Audit basics', 'Regulatory awareness'],
                    'expected_behaviors' => ['Ethical', 'Diligent'],
                ],
                [
                    'key' => 'judgement', 'title' => 'Business Judgement',
                    'objective' => 'Gauge translating numbers into business recommendations.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask for a recommendation from a financial scenario and the rationale.',
                    'scoring_rules' => ['Reward decisions tied to the numbers.', 'Reward clear communication to non-finance peers.'],
                    'follow_up_rules' => ['Ask how they would present this to leadership.'],
                    'expected_skills' => ['Business partnering', 'Communication', 'Decision support'],
                    'expected_behaviors' => ['Pragmatic', 'Clear communicator'],
                ],
            ],
        ],

        'legal' => [
            'name'        => 'Legal Counsel',
            'role_family' => 'legal',
            'description' => 'Legal interview covering analysis, risk, drafting and ethics.',
            'objectives'  => [
                'Assess legal reasoning and issue spotting.',
                'Evaluate risk assessment and pragmatism.',
                'Gauge drafting clarity and ethics.',
            ],
            'evaluation_criteria' => [
                'Legal analysis',
                'Risk assessment',
                'Drafting and communication',
                'Ethics and judgement',
            ],
            'sections' => [
                [
                    'key' => 'legal_analysis', 'title' => 'Legal Analysis',
                    'objective' => 'Probe issue spotting and reasoning from a fact pattern.',
                    'weight' => 30, 'difficulty' => 'hard',
                    'question_strategy' => 'Give a fact pattern; ask them to spot issues and reason to a conclusion.',
                    'scoring_rules' => ['Reward thorough issue spotting.', 'Reward sound reasoning over a confident guess.'],
                    'follow_up_rules' => ['Change a fact and ask how the analysis shifts.'],
                    'expected_skills' => ['Issue spotting', 'Legal research', 'Statutory interpretation'],
                    'expected_behaviors' => ['Analytical', 'Thorough'],
                ],
                [
                    'key' => 'risk', 'title' => 'Risk Assessment',
                    'objective' => 'Assess balancing legal risk against business needs.',
                    'weight' => 26, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask how they advised the business on a risky decision.',
                    'scoring_rules' => ['Reward pragmatic, business-aware risk advice.', 'Reward clear articulation of worst case.'],
                    'follow_up_rules' => ['Ask how they handle a business that wants to proceed against advice.'],
                    'expected_skills' => ['Risk analysis', 'Negotiation', 'Commercial awareness'],
                    'expected_behaviors' => ['Pragmatic', 'Balanced'],
                ],
                [
                    'key' => 'drafting', 'title' => 'Drafting & Communication',
                    'objective' => 'Evaluate clear drafting and plain-language advice.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask them to explain a clause and its risk in plain language.',
                    'scoring_rules' => ['Reward precise yet readable drafting.', 'Reward translating legalese for the business.'],
                    'follow_up_rules' => ['Ask how they would tighten an ambiguous clause.'],
                    'expected_skills' => ['Contract drafting', 'Plain-language writing', 'Attention to detail'],
                    'expected_behaviors' => ['Precise', 'Clear communicator'],
                ],
                [
                    'key' => 'ethics', 'title' => 'Ethics & Judgement',
                    'objective' => 'Gauge professional ethics and handling conflicts.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Pose an ethical dilemma and observe their reasoning.',
                    'scoring_rules' => ['Reward firm ethical lines.', 'Reward escalation when appropriate.'],
                    'follow_up_rules' => ['Ask about a time they pushed back on leadership.'],
                    'expected_skills' => ['Professional responsibility', 'Conflict checks', 'Confidentiality'],
                    'expected_behaviors' => ['Principled', 'Discreet'],
                ],
            ],
        ],

        'healthcare' => [
            'name'        => 'Healthcare Professional',
            'role_family' => 'healthcare',
            'description' => 'Healthcare interview covering clinical knowledge, patient care, safety and teamwork.',
            'objectives'  => [
                'Assess clinical knowledge and judgement.',
                'Evaluate patient-centered care and empathy.',
                'Gauge safety, compliance and teamwork.',
            ],
            'evaluation_criteria' => [
                'Clinical knowledge',
                'Patient care and empathy',
                'Safety and compliance',
                'Teamwork and communication',
            ],
            'sections' => [
                [
                    'key' => 'clinical_knowledge', 'title' => 'Clinical Knowledge',
                    'objective' => 'Probe role-appropriate clinical knowledge and reasoning.',
                    'weight' => 30, 'difficulty' => 'hard',
                    'question_strategy' => 'Use a clinical scenario; assess assessment, reasoning and prioritization.',
                    'scoring_rules' => ['Reward correct prioritization of patient needs.', 'Reward evidence-based reasoning.'],
                    'follow_up_rules' => ['Change a symptom and ask how the plan changes.'],
                    'expected_skills' => ['Clinical assessment', 'Evidence-based practice', 'Prioritization'],
                    'expected_behaviors' => ['Careful', 'Methodical'],
                ],
                [
                    'key' => 'patient_care', 'title' => 'Patient Care & Empathy',
                    'objective' => 'Evaluate compassionate, patient-centered communication.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Role-play delivering difficult news or calming an anxious patient.',
                    'scoring_rules' => ['Reward empathy with clarity.', 'Reward respecting patient dignity.'],
                    'follow_up_rules' => ['Ask how they handle a non-compliant patient.'],
                    'expected_skills' => ['Patient communication', 'Empathy', 'Health literacy awareness'],
                    'expected_behaviors' => ['Compassionate', 'Respectful'],
                ],
                [
                    'key' => 'safety', 'title' => 'Safety & Compliance',
                    'objective' => 'Assess patient safety, hygiene and regulatory compliance.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about a safety risk they caught or a protocol they follow strictly.',
                    'scoring_rules' => ['Reward strict safety and privacy practices.', 'Reward speaking up about risks.'],
                    'follow_up_rules' => ['Ask how they report a near-miss.'],
                    'expected_skills' => ['Patient safety', 'Infection control', 'Privacy/compliance'],
                    'expected_behaviors' => ['Conscientious', 'Vigilant'],
                ],
                [
                    'key' => 'teamwork', 'title' => 'Teamwork & Communication',
                    'objective' => 'Gauge collaboration within a care team under pressure.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about coordinating care in a high-pressure situation.',
                    'scoring_rules' => ['Reward clear handoffs and teamwork.'],
                    'follow_up_rules' => ['Ask how they handled a disagreement with a colleague.'],
                    'expected_skills' => ['Care coordination', 'Handoff communication', 'Collaboration'],
                    'expected_behaviors' => ['Team-oriented', 'Calm under pressure'],
                ],
            ],
        ],

        'education' => [
            'name'        => 'Educator',
            'role_family' => 'education',
            'description' => 'Education interview covering subject mastery, pedagogy, classroom management and care.',
            'objectives'  => [
                'Assess subject mastery and lesson design.',
                'Evaluate pedagogy and engagement.',
                'Gauge classroom management and student care.',
            ],
            'evaluation_criteria' => [
                'Subject mastery',
                'Pedagogy and lesson design',
                'Classroom management',
                'Student care and inclusion',
            ],
            'sections' => [
                [
                    'key' => 'subject_mastery', 'title' => 'Subject Mastery',
                    'objective' => 'Confirm command of the subject and how to make it accessible.',
                    'weight' => 28, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask them to explain a hard concept to a struggling student.',
                    'scoring_rules' => ['Reward accurate, accessible explanations.', 'Reward multiple representations of an idea.'],
                    'follow_up_rules' => ['Ask how they correct a common misconception.'],
                    'expected_skills' => ['Subject expertise', 'Explaining clearly', 'Curriculum knowledge'],
                    'expected_behaviors' => ['Knowledgeable', 'Patient'],
                ],
                [
                    'key' => 'pedagogy', 'title' => 'Pedagogy & Engagement',
                    'objective' => 'Evaluate lesson design and keeping students engaged.',
                    'weight' => 28, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask them to outline an engaging lesson and its learning goals.',
                    'scoring_rules' => ['Reward clear objectives and active learning.', 'Reward assessment for understanding.'],
                    'follow_up_rules' => ['Ask how they adapt when students are lost.'],
                    'expected_skills' => ['Lesson planning', 'Differentiation', 'Formative assessment'],
                    'expected_behaviors' => ['Creative', 'Adaptive'],
                ],
                [
                    'key' => 'classroom_management', 'title' => 'Classroom Management',
                    'objective' => 'Assess maintaining a productive, respectful classroom.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they handled a disruptive class or student.',
                    'scoring_rules' => ['Reward fair, consistent expectations.', 'Reward de-escalation over punishment.'],
                    'follow_up_rules' => ['Ask how they build a positive class culture.'],
                    'expected_skills' => ['Behavior management', 'Routines and structure', 'De-escalation'],
                    'expected_behaviors' => ['Firm and fair', 'Calm'],
                ],
                [
                    'key' => 'student_care', 'title' => 'Student Care & Inclusion',
                    'objective' => 'Gauge supporting diverse learners and their wellbeing.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask how they supported a struggling or marginalized student.',
                    'scoring_rules' => ['Reward inclusive, individualized support.'],
                    'follow_up_rules' => ['Ask how they involve families.'],
                    'expected_skills' => ['Inclusive teaching', 'Student support', 'Communication with families'],
                    'expected_behaviors' => ['Caring', 'Inclusive'],
                ],
            ],
        ],

        'hospitality' => [
            'name'        => 'Hospitality Professional',
            'role_family' => 'hospitality',
            'description' => 'Hospitality interview covering guest service, operations, problem solving and teamwork.',
            'objectives'  => [
                'Assess guest-service orientation.',
                'Evaluate operations and attention to detail.',
                'Gauge problem solving and teamwork under pressure.',
            ],
            'evaluation_criteria' => [
                'Guest service',
                'Operational excellence',
                'Problem solving',
                'Teamwork and composure',
            ],
            'sections' => [
                [
                    'key' => 'guest_service', 'title' => 'Guest Service',
                    'objective' => 'Evaluate creating a warm, memorable guest experience.',
                    'weight' => 30, 'difficulty' => 'easy',
                    'question_strategy' => 'Role-play greeting and serving a guest; assess warmth and attentiveness.',
                    'scoring_rules' => ['Reward anticipating guest needs.', 'Reward genuine warmth.'],
                    'follow_up_rules' => ['Introduce a demanding guest and observe response.'],
                    'expected_skills' => ['Guest interaction', 'Anticipating needs', 'Upselling tactfully'],
                    'expected_behaviors' => ['Warm', 'Attentive'],
                ],
                [
                    'key' => 'operations', 'title' => 'Operational Excellence',
                    'objective' => 'Assess attention to detail and standards in daily operations.',
                    'weight' => 24, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask how they maintain standards during a busy shift.',
                    'scoring_rules' => ['Reward consistency and cleanliness standards.', 'Reward efficient workflow.'],
                    'follow_up_rules' => ['Ask how they handle a supply or staffing shortfall.'],
                    'expected_skills' => ['Service standards', 'Time management', 'Attention to detail'],
                    'expected_behaviors' => ['Detail-oriented', 'Reliable'],
                ],
                [
                    'key' => 'problem_solving', 'title' => 'Problem Solving',
                    'objective' => 'Evaluate recovering gracefully from a service failure.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Give a service-failure scenario and observe the recovery.',
                    'scoring_rules' => ['Reward quick, guest-first recovery.', 'Reward ownership over blame.'],
                    'follow_up_rules' => ['Ask how they turn a complaint into loyalty.'],
                    'expected_skills' => ['Service recovery', 'Decision-making', 'Empowerment'],
                    'expected_behaviors' => ['Resourceful', 'Guest-first'],
                ],
                [
                    'key' => 'teamwork', 'title' => 'Teamwork & Composure',
                    'objective' => 'Gauge collaboration and composure during a rush.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about working as a team during a peak rush.',
                    'scoring_rules' => ['Reward helping teammates under pressure.'],
                    'follow_up_rules' => ['Ask how they stay positive on a hard shift.'],
                    'expected_skills' => ['Teamwork', 'Stress management', 'Communication'],
                    'expected_behaviors' => ['Supportive', 'Composed'],
                ],
            ],
        ],

        // ── Leadership & programs ──────────────────────────────────────────
        'executive' => [
            'name'        => 'Executive / Leadership',
            'role_family' => 'leadership',
            'description' => 'Executive interview covering vision, leadership, business acumen and decision-making.',
            'objectives'  => [
                'Assess strategic vision and business acumen.',
                'Evaluate leadership and people development.',
                'Gauge judgement and stakeholder influence.',
            ],
            'evaluation_criteria' => [
                'Strategic vision',
                'Leadership and people',
                'Business acumen',
                'Judgement and influence',
            ],
            'sections' => [
                [
                    'key' => 'vision', 'title' => 'Vision & Strategy',
                    'objective' => 'Evaluate setting and communicating a compelling strategy.',
                    'weight' => 28, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask them to define a strategy for an ambiguous market situation.',
                    'scoring_rules' => ['Reward a clear, differentiated vision.', 'Reward linking strategy to execution.'],
                    'follow_up_rules' => ['Ask how they would pivot if the market shifts.'],
                    'expected_skills' => ['Strategic planning', 'Market insight', 'Vision communication'],
                    'expected_behaviors' => ['Visionary', 'Decisive'],
                ],
                [
                    'key' => 'leadership', 'title' => 'Leadership & People',
                    'objective' => 'Assess building, leading and developing high-performing teams.',
                    'weight' => 28, 'difficulty' => 'hard',
                    'question_strategy' => 'Use STAR prompts on turning around or scaling a team.',
                    'scoring_rules' => ['Reward developing leaders, not just managing.', 'Reward handling underperformance with care.'],
                    'follow_up_rules' => ['Ask about a hard people decision they made.'],
                    'expected_skills' => ['Team building', 'Coaching', 'Change leadership'],
                    'expected_behaviors' => ['Inspiring', 'Accountable'],
                ],
                [
                    'key' => 'business_acumen', 'title' => 'Business Acumen',
                    'objective' => 'Evaluate command of the numbers and operating levers.',
                    'weight' => 24, 'difficulty' => 'hard',
                    'question_strategy' => 'Ask how they improved a key business metric and the tradeoffs involved.',
                    'scoring_rules' => ['Reward data-driven decisions.', 'Reward balancing growth and sustainability.'],
                    'follow_up_rules' => ['Ask about a costly mistake and the lesson.'],
                    'expected_skills' => ['Financial acumen', 'Operational excellence', 'Prioritization'],
                    'expected_behaviors' => ['Results-driven', 'Pragmatic'],
                ],
                [
                    'key' => 'judgement', 'title' => 'Judgement & Influence',
                    'objective' => 'Gauge high-stakes decision-making and stakeholder influence.',
                    'weight' => 20, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about a high-stakes decision made with incomplete information.',
                    'scoring_rules' => ['Reward sound judgement under uncertainty.', 'Reward aligning diverse stakeholders.'],
                    'follow_up_rules' => ['Ask how they handled board or investor pressure.'],
                    'expected_skills' => ['Decision-making', 'Stakeholder management', 'Communication'],
                    'expected_behaviors' => ['Composed', 'Influential'],
                ],
            ],
        ],

        'internship' => [
            'name'        => 'Internship',
            'role_family' => 'early_career',
            'description' => 'Internship interview focused on potential, fundamentals and attitude.',
            'objectives'  => [
                'Assess foundational knowledge for the field.',
                'Evaluate eagerness to learn and coachability.',
                'Gauge teamwork and communication.',
            ],
            'evaluation_criteria' => [
                'Foundational knowledge',
                'Learning attitude',
                'Communication',
                'Teamwork and fit',
            ],
            'sections' => [
                [
                    'key' => 'fundamentals', 'title' => 'Foundational Knowledge',
                    'objective' => 'Confirm relevant coursework or basic skills for the role.',
                    'weight' => 30, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about a relevant project or class and probe what they actually did.',
                    'scoring_rules' => ['Reward genuine understanding over buzzwords.', 'Credit hands-on experience.'],
                    'follow_up_rules' => ['Ask what they would do differently next time.'],
                    'expected_skills' => ['Relevant fundamentals', 'Applying coursework', 'Tooling basics'],
                    'expected_behaviors' => ['Honest', 'Reflective'],
                ],
                [
                    'key' => 'learning', 'title' => 'Learning Attitude',
                    'objective' => 'Evaluate curiosity and how they learn new things.',
                    'weight' => 28, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about something they taught themselves recently.',
                    'scoring_rules' => ['Reward initiative and self-direction.'],
                    'follow_up_rules' => ['Ask how they would ramp on something unfamiliar.'],
                    'expected_skills' => ['Self-directed learning', 'Resourcefulness'],
                    'expected_behaviors' => ['Curious', 'Coachable'],
                ],
                [
                    'key' => 'communication', 'title' => 'Communication',
                    'objective' => 'Assess explaining ideas clearly and asking for help.',
                    'weight' => 22, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask them to explain a project simply and how they ask for help.',
                    'scoring_rules' => ['Reward clarity and structure.'],
                    'follow_up_rules' => ['Ask how they handle not understanding a task.'],
                    'expected_skills' => ['Clear explanation', 'Asking questions'],
                    'expected_behaviors' => ['Communicative', 'Humble'],
                ],
                [
                    'key' => 'teamwork', 'title' => 'Teamwork & Fit',
                    'objective' => 'Gauge collaboration and motivation for the internship.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about a team project and why they want this internship.',
                    'scoring_rules' => ['Reward genuine motivation and teamwork.'],
                    'follow_up_rules' => ['Ask what they hope to learn here.'],
                    'expected_skills' => ['Collaboration', 'Time management'],
                    'expected_behaviors' => ['Enthusiastic', 'Reliable'],
                ],
            ],
        ],

        'graduate_program' => [
            'name'        => 'Graduate Program',
            'role_family' => 'early_career',
            'description' => 'Graduate program interview covering aptitude, fundamentals, potential and values.',
            'objectives'  => [
                'Assess analytical aptitude and fundamentals.',
                'Evaluate growth potential and ambition.',
                'Gauge values alignment and teamwork.',
            ],
            'evaluation_criteria' => [
                'Analytical aptitude',
                'Domain fundamentals',
                'Growth potential',
                'Values and teamwork',
            ],
            'sections' => [
                [
                    'key' => 'aptitude', 'title' => 'Analytical Aptitude',
                    'objective' => 'Evaluate structured reasoning on an unfamiliar problem.',
                    'weight' => 30, 'difficulty' => 'medium',
                    'question_strategy' => 'Pose a brain-teaser or estimation question; reward the approach.',
                    'scoring_rules' => ['Reward structured reasoning over the final number.', 'Reward stating assumptions.'],
                    'follow_up_rules' => ['Change an assumption and ask them to redo the estimate.'],
                    'expected_skills' => ['Structured thinking', 'Estimation', 'Logical reasoning'],
                    'expected_behaviors' => ['Composed', 'Methodical'],
                ],
                [
                    'key' => 'fundamentals', 'title' => 'Domain Fundamentals',
                    'objective' => 'Confirm core knowledge from their degree relevant to the track.',
                    'weight' => 26, 'difficulty' => 'medium',
                    'question_strategy' => 'Ask about their strongest subject and probe one concept in depth.',
                    'scoring_rules' => ['Reward depth in at least one area.', 'Credit applying theory to practice.'],
                    'follow_up_rules' => ['Ask for a real application of the concept.'],
                    'expected_skills' => ['Relevant fundamentals', 'Applying theory'],
                    'expected_behaviors' => ['Knowledgeable', 'Honest about gaps'],
                ],
                [
                    'key' => 'potential', 'title' => 'Growth Potential',
                    'objective' => 'Assess ambition, resilience and learning velocity.',
                    'weight' => 24, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about a goal they pursued and an obstacle they overcame.',
                    'scoring_rules' => ['Reward resilience and self-improvement.'],
                    'follow_up_rules' => ['Ask where they want to be in a few years.'],
                    'expected_skills' => ['Self-directed learning', 'Goal setting'],
                    'expected_behaviors' => ['Ambitious', 'Resilient'],
                ],
                [
                    'key' => 'values', 'title' => 'Values & Teamwork',
                    'objective' => 'Gauge values alignment and collaboration.',
                    'weight' => 20, 'difficulty' => 'easy',
                    'question_strategy' => 'Ask about a team setback and their role in it.',
                    'scoring_rules' => ['Reward accountability and team-first thinking.'],
                    'follow_up_rules' => ['Ask what they value in a team.'],
                    'expected_skills' => ['Collaboration', 'Self-awareness'],
                    'expected_behaviors' => ['Team-oriented', 'Values-driven'],
                ],
            ],
        ],

    ],
];
