<?php
/** @var array<string,mixed> $offer */
/** @var array<string,mixed>|null $workspace */
?>
<div class="mb-8 flex items-center justify-between border-b border-slate-200 pb-6">
    <div>
        <div class="text-lg font-bold text-slate-900"><?= e($workspace['name'] ?? 'Company') ?></div>
        <div class="text-xs text-slate-400">Offer of employment</div>
    </div>
    <div class="text-right text-xs text-slate-400">Ref: <?= e(substr((string) $offer['id'], -8)) ?><br><?= e(substr((string) ($offer['created_at'] ?? ''), 0, 10)) ?></div>
</div>

<p class="text-sm text-slate-700">Dear <strong><?= e($offer['candidate_name']) ?></strong>,</p>
<p class="mt-4 text-sm leading-relaxed text-slate-700">
    We are pleased to offer you the position of <strong><?= e($offer['title'] ?: $offer['job_title']) ?></strong>
    at <?= e($workspace['name'] ?? 'our company') ?>.
    <?php if ($offer['salary'] !== null): ?>
        The proposed compensation is <strong><?= e(number_format((float) $offer['salary'])) ?> <?= e($offer['currency']) ?></strong>.
    <?php endif; ?>
</p>

<?php if (! empty($offer['note'])): ?>
    <div class="mt-4 rounded-lg bg-slate-50 p-4 text-sm text-slate-600"><?= nl2br(e((string) $offer['note'])) ?></div>
<?php endif; ?>

<dl class="mt-8 grid grid-cols-2 gap-y-2 text-sm">
    <dt class="text-slate-400">Role</dt><dd class="text-slate-800"><?= e($offer['title'] ?: $offer['job_title']) ?></dd>
    <dt class="text-slate-400">Candidate</dt><dd class="text-slate-800"><?= e($offer['candidate_name']) ?> · <?= e($offer['candidate_email'] ?? '') ?></dd>
    <dt class="text-slate-400">Status</dt><dd class="text-slate-800 capitalize"><?= e($offer['status']) ?></dd>
</dl>

<p class="mt-10 text-sm text-slate-700">Sincerely,<br>The hiring team at <?= e($workspace['name'] ?? 'the company') ?></p>
<p class="mt-12 border-t border-slate-200 pt-4 text-xs text-slate-400">This letter was generated by HaHireAI. Signatures and legal terms apply per your employment agreement.</p>
